server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ks?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

    # MyBatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.baidu.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**Mapper.xml
